-- ============================================================================
-- LEO BUSINESS ADVISORY — Production Initial Setup
--
-- Generated by concatenating supabase/migrations/0001_init_schema.sql
-- through 0007_gallery_soft_delete.sql, in that exact numeric order, with
-- no SQL statement added, removed, or altered — every table, column, RLS
-- policy, function, trigger, and Storage policy below is byte-identical
-- in meaning to its source migration file. Section dividers below name
-- the source file each block came from, purely for traceability back to
-- supabase/migrations/.
--
-- INTENDED USE: apply this ONCE, in full, top to bottom, in the Supabase
-- SQL Editor of a brand-new project that has none of these objects yet.
-- It is NOT safe to run a second time against the same project — most
-- `create policy` statements below have no `if not exists` guard (Postgres
-- doesn't support one for policies), matching the original migration
-- files exactly; a second run will fail the first time it hits an
-- already-existing policy. This mirrors the source migrations' own
-- behavior — no duplicate-execution guard has been added here that
-- wasn't already present in a given file.
--
-- AFTER running this file, one manual step still has to happen outside
-- SQL (see supabase/README.md and 0002's own header comment below): no
-- one has admin access yet. Create your admin login in the Supabase
-- Dashboard (Authentication → Users → Add user), copy that user's UUID,
-- then run this once, by itself, with the real UUID substituted in:
--
--   insert into admin_users (user_id) values ('<uuid from auth.users>');
--
-- Until that insert runs, RLS on every content table denies all writes
-- to everyone (including a logged-in user) — this is expected, not a
-- bug: public read continues to work throughout.
-- ============================================================================


-- ============================================================================
-- SOURCE: supabase/migrations/0001_init_schema.sql
-- ============================================================================

-- ============================================================================
-- LEO Business Advisory — Admin CMS schema (Phase 2-A design)
--
-- Mirrors src/data/profile.js field-for-field, so a future migration can
-- map values across 1:1 with minimal risk of introducing fact drift.
-- Every bilingual field uses the same _ko/_en column-pair convention
-- already used throughout profile.js — see
-- docs/ADMIN_CMS_ARCHITECTURE.md for the full rationale.
--
-- This file is NOT applied to any real Supabase project yet — no project
-- exists. Run it yourself in the Supabase SQL Editor (or `supabase db
-- push`) once you've created one. See supabase/README.md.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Media library — every uploaded image lives here once; content tables
-- reference it by id instead of duplicating storage paths. storage_path
-- is the object path inside the "site-images" bucket (see
-- 0003_storage_setup.sql).
-- ---------------------------------------------------------------------------
create table if not exists media (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  alt_ko text,
  alt_en text,
  width integer,
  height integer,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Singleton content tables — exactly one row each (id fixed to 1 via the
-- check constraint, so there's never an "which row is live?" ambiguity).
-- ---------------------------------------------------------------------------

create table if not exists site_settings (
  id integer primary key default 1 check (id = 1),
  name text not null,
  title_tag text not null,
  description_en text not null,
  updated_at timestamptz not null default now()
);

create table if not exists person (
  id integer primary key default 1 check (id = 1),
  name_ko text not null,
  name_ko_formatted text not null,
  name_en text not null,
  name_en_display text not null,
  title_ko text not null,
  title_en text not null,
  positioning_ko text not null,
  positioning_en text not null,
  portrait_label_ko text not null,
  portrait_label_en text not null,
  updated_at timestamptz not null default now()
);

-- mailto:/tel: hrefs are derived from email/phone_display in application
-- code, not stored here, so they can never drift out of sync with the
-- displayed value.
create table if not exists contact_info (
  id integer primary key default 1 check (id = 1),
  location_ko text not null,
  location_en text not null,
  email text not null,
  phone_display text not null,
  info_label_ko text not null,
  info_label_en text not null,
  updated_at timestamptz not null default now()
);

create table if not exists hero_content (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null,
  eyebrow_en text not null,
  headline_ko jsonb not null, -- array of lines, e.g. ["Building Brands.", "Scaling Businesses.", ...]
  headline_en jsonb not null,
  subhead_ko text not null,
  subhead_en text not null,
  cta_primary_ko text not null,
  cta_primary_en text not null,
  cta_primary_target text not null, -- target section id, e.g. "impact"
  cta_secondary_ko text not null,
  cta_secondary_en text not null,
  cta_secondary_target text not null,
  hero_image_id uuid references media(id),
  updated_at timestamptz not null default now()
);

create table if not exists about_content (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null,
  eyebrow_en text not null,
  headline_ko text not null,
  headline_en text not null,
  bio_ko text not null,
  bio_en text not null,
  portrait_image_id uuid references media(id),
  updated_at timestamptz not null default now()
);

-- Section heading copy (eyebrow + title) for the sections whose body
-- content is a list, rendered from the list tables below. Kept separate
-- from those lists so editing a heading never risks touching list rows.
create table if not exists impact_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists case_studies_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists advisory_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists career_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists gallery_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null,
  empty_ko text not null, empty_en text not null -- shown when gallery_items has 0 rows
);

create table if not exists contact_cta (
  id integer primary key default 1 check (id = 1),
  headline_ko text not null, headline_en text not null,
  button_ko text not null, button_en text not null
);

-- `labels` shape: { "name": {"ko":"이름","en":"Name"}, "company": {...},
-- "email": {...}, "inquiryType": {...}, "message": {...} } — mirrors
-- profile.js contactForm.labels exactly.
create table if not exists contact_form_content (
  id integer primary key default 1 check (id = 1),
  labels jsonb not null,
  inquiry_placeholder_ko text not null,
  inquiry_placeholder_en text not null,
  submit_ko text not null,
  submit_en text not null,
  note_ko text not null,
  note_en text not null
);

create table if not exists footer_content (
  id integer primary key default 1 check (id = 1),
  copyright_ko text not null, copyright_en text not null,
  back_to_top_ko text not null, back_to_top_en text not null
);

-- ---------------------------------------------------------------------------
-- List content — ordered via sort_order (lets the admin UI reorder rows
-- without changing any other data).
-- ---------------------------------------------------------------------------

create table if not exists impact_metrics (
  id uuid primary key default gen_random_uuid(),
  value_ko text not null, label_ko text not null,
  value_en text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists case_studies (
  id uuid primary key default gen_random_uuid(),
  case_key text not null unique, -- stable slug, matches profile.js caseStudies[].id (e.g. "samsonite-korea")
  tag text not null, -- e.g. "CASE 01"
  title_ko text not null, title_en text not null,
  summary_ko text not null, summary_en text not null,
  image_id uuid references media(id),
  sort_order integer not null default 0
);

create table if not exists case_study_metrics (
  id uuid primary key default gen_random_uuid(),
  case_study_id uuid not null references case_studies(id) on delete cascade,
  value_ko text not null, label_ko text not null,
  value_en text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists case_study_highlights (
  id uuid primary key default gen_random_uuid(),
  case_study_id uuid not null references case_studies(id) on delete cascade,
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists advisory_items (
  id uuid primary key default gen_random_uuid(),
  item_key text not null unique, -- matches profile.js advisory.items[].id
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists career_entries (
  id uuid primary key default gen_random_uuid(),
  period text not null, -- e.g. "2013–2015"
  role_ko text not null, role_en text not null,
  company_ko text not null, company_en text not null,
  sort_order integer not null default 0
);

create table if not exists education_entries (
  id uuid primary key default gen_random_uuid(),
  text_ko text not null, text_en text not null,
  sort_order integer not null default 0
);

create table if not exists inquiry_types (
  id uuid primary key default gen_random_uuid(),
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists gallery_items (
  id uuid primary key default gen_random_uuid(),
  item_key text not null unique, -- matches profile.js gallery[].id
  caption_ko text not null, caption_en text not null,
  image_id uuid references media(id),
  aspect_ratio text not null default '4 / 3', -- CSS aspect-ratio value
  is_wide boolean not null default false,
  sort_order integer not null default 0
);


-- ============================================================================
-- SOURCE: supabase/migrations/0002_rls_policies.sql
-- ============================================================================

-- ============================================================================
-- Row Level Security — public read, admin-only write.
--
-- Run this AFTER 0001_init_schema.sql. admin_users lists which Supabase
-- Auth users are allowed to write content — nobody can just sign up and
-- get write access. After creating your admin login (Supabase Dashboard
-- → Authentication → Users → Add user, or have them sign up once), find
-- their id in that same screen and run:
--
--   insert into admin_users (user_id) values ('<uuid from auth.users>');
-- ============================================================================

create table if not exists admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table admin_users enable row level security;
-- Deliberately no public policies on admin_users — nobody reads/writes it
-- from the client at all; membership is managed directly in the SQL
-- editor by whoever has Supabase project access.

-- `set search_path` pins this security-definer function to the `public`
-- schema (plus pg_temp, needed for temp objects) so a caller can't shadow
-- `admin_users` by creating a same-named table/function earlier in their
-- own search_path — the standard hardening for SECURITY DEFINER
-- functions (Phase 2-G security pass).
create or replace function is_admin()
returns boolean
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select exists (select 1 from admin_users where user_id = auth.uid());
$$;

-- Every content table: anyone (including a signed-out visitor) can read;
-- only a row in admin_users can write. Run each pair after its table
-- exists (i.e. after 0001_init_schema.sql).

alter table site_settings enable row level security;
create policy "site_settings_public_read" on site_settings for select using (true);
create policy "site_settings_admin_write" on site_settings for all using (is_admin()) with check (is_admin());

alter table person enable row level security;
create policy "person_public_read" on person for select using (true);
create policy "person_admin_write" on person for all using (is_admin()) with check (is_admin());

alter table contact_info enable row level security;
create policy "contact_info_public_read" on contact_info for select using (true);
create policy "contact_info_admin_write" on contact_info for all using (is_admin()) with check (is_admin());

alter table hero_content enable row level security;
create policy "hero_content_public_read" on hero_content for select using (true);
create policy "hero_content_admin_write" on hero_content for all using (is_admin()) with check (is_admin());

alter table about_content enable row level security;
create policy "about_content_public_read" on about_content for select using (true);
create policy "about_content_admin_write" on about_content for all using (is_admin()) with check (is_admin());

alter table impact_section enable row level security;
create policy "impact_section_public_read" on impact_section for select using (true);
create policy "impact_section_admin_write" on impact_section for all using (is_admin()) with check (is_admin());

alter table case_studies_section enable row level security;
create policy "case_studies_section_public_read" on case_studies_section for select using (true);
create policy "case_studies_section_admin_write" on case_studies_section for all using (is_admin()) with check (is_admin());

alter table advisory_section enable row level security;
create policy "advisory_section_public_read" on advisory_section for select using (true);
create policy "advisory_section_admin_write" on advisory_section for all using (is_admin()) with check (is_admin());

alter table career_section enable row level security;
create policy "career_section_public_read" on career_section for select using (true);
create policy "career_section_admin_write" on career_section for all using (is_admin()) with check (is_admin());

alter table gallery_section enable row level security;
create policy "gallery_section_public_read" on gallery_section for select using (true);
create policy "gallery_section_admin_write" on gallery_section for all using (is_admin()) with check (is_admin());

alter table contact_cta enable row level security;
create policy "contact_cta_public_read" on contact_cta for select using (true);
create policy "contact_cta_admin_write" on contact_cta for all using (is_admin()) with check (is_admin());

alter table contact_form_content enable row level security;
create policy "contact_form_content_public_read" on contact_form_content for select using (true);
create policy "contact_form_content_admin_write" on contact_form_content for all using (is_admin()) with check (is_admin());

alter table footer_content enable row level security;
create policy "footer_content_public_read" on footer_content for select using (true);
create policy "footer_content_admin_write" on footer_content for all using (is_admin()) with check (is_admin());

alter table media enable row level security;
create policy "media_public_read" on media for select using (true);
create policy "media_admin_write" on media for all using (is_admin()) with check (is_admin());

alter table impact_metrics enable row level security;
create policy "impact_metrics_public_read" on impact_metrics for select using (true);
create policy "impact_metrics_admin_write" on impact_metrics for all using (is_admin()) with check (is_admin());

alter table case_studies enable row level security;
create policy "case_studies_public_read" on case_studies for select using (true);
create policy "case_studies_admin_write" on case_studies for all using (is_admin()) with check (is_admin());

alter table case_study_metrics enable row level security;
create policy "case_study_metrics_public_read" on case_study_metrics for select using (true);
create policy "case_study_metrics_admin_write" on case_study_metrics for all using (is_admin()) with check (is_admin());

alter table case_study_highlights enable row level security;
create policy "case_study_highlights_public_read" on case_study_highlights for select using (true);
create policy "case_study_highlights_admin_write" on case_study_highlights for all using (is_admin()) with check (is_admin());

alter table advisory_items enable row level security;
create policy "advisory_items_public_read" on advisory_items for select using (true);
create policy "advisory_items_admin_write" on advisory_items for all using (is_admin()) with check (is_admin());

alter table career_entries enable row level security;
create policy "career_entries_public_read" on career_entries for select using (true);
create policy "career_entries_admin_write" on career_entries for all using (is_admin()) with check (is_admin());

alter table education_entries enable row level security;
create policy "education_entries_public_read" on education_entries for select using (true);
create policy "education_entries_admin_write" on education_entries for all using (is_admin()) with check (is_admin());

alter table inquiry_types enable row level security;
create policy "inquiry_types_public_read" on inquiry_types for select using (true);
create policy "inquiry_types_admin_write" on inquiry_types for all using (is_admin()) with check (is_admin());

alter table gallery_items enable row level security;
create policy "gallery_items_public_read" on gallery_items for select using (true);
create policy "gallery_items_admin_write" on gallery_items for all using (is_admin()) with check (is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0003_storage_setup.sql
-- ============================================================================

-- ============================================================================
-- Storage bucket for site images.
--
-- Run this AFTER 0002_rls_policies.sql (it depends on admin_users/is_admin()).
--
-- Bucket "site-images" is public-read (this is a public marketing site —
-- there's no reason to gate image loads behind signed URLs) and
-- admin-write only. Suggested folder layout inside the bucket, purely for
-- your own organization (Storage doesn't enforce folder structure) —
-- mirrors profile.js's existing image slots:
--   site-images/hero/
--   site-images/about/
--   site-images/case-studies/
--   site-images/gallery/
-- ============================================================================

-- file_size_limit / allowed_mime_types enforce the same limits as the
-- admin's client-side check (src/admin/content/supabaseStorage.js)
-- server-side too — the client check alone only stops an honest mistake,
-- not a direct API call with a valid admin session, so both layers exist
-- (Phase 2-G security pass).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-images',
  'site-images',
  true,
  5242880, -- 5 MB, matches MAX_IMAGE_BYTES
  array['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'] -- matches ALLOWED_IMAGE_TYPES
)
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "site_images_public_read"
  on storage.objects for select
  using (bucket_id = 'site-images');

create policy "site_images_admin_insert"
  on storage.objects for insert
  with check (bucket_id = 'site-images' and is_admin());

create policy "site_images_admin_update"
  on storage.objects for update
  using (bucket_id = 'site-images' and is_admin());

create policy "site_images_admin_delete"
  on storage.objects for delete
  using (bucket_id = 'site-images' and is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0004_gallery_active_flag.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-B — Gallery active/inactive flag
--
-- Lets an admin temporarily hide a gallery photo (e.g. a photo pending
-- replacement, or one that no longer fits) without deleting its row —
-- deleting also permanently removes the underlying Storage file and media
-- row, which isn't reversible. Adding a boolean flag instead makes hiding
-- a photo a safe, undoable action.
--
-- `default true` so every existing gallery_items row (and any inserted by
-- older client code that doesn't know about this column yet) stays visible
-- with no migration-time data change needed.
--
-- Admin-side only in this phase: src/admin/pages/images/GalleryImages.jsx
-- reads and writes this column, but the public site's gallery query
-- (src/lib/content/gallery.js) is intentionally left untouched — see
-- docs/PROJECT_STATUS.md's Phase 3-B entry for why, and Phase 3-C for the
-- planned follow-up.
-- ============================================================================

alter table gallery_items
  add column if not exists is_active boolean not null default true;


-- ============================================================================
-- SOURCE: supabase/migrations/0005_inquiries.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-C — Business inquiries (Contact Form submissions)
--
-- A visitor-submitted table, unlike every other table in this schema
-- (which are all admin-authored site content). RLS here is the opposite
-- shape from 0002_rls_policies.sql's public-read/admin-write pattern:
-- anyone can INSERT (that's the whole point of a public contact form),
-- nobody but an admin can ever read, update, or delete a row.
--
-- `phone` is nullable and not currently collected by the public form
-- (src/components/ContactForm.jsx keeps only Name/Company/Email/Type of
-- Inquiry/Message, per this phase's explicit "don't add fields that
-- increase visitor input burden" instruction) — the column exists so a
-- future optional Phone field needs only a form change, not a migration.
-- ============================================================================

create table if not exists inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(name) between 1 and 200),
  company text check (company is null or length(company) <= 200),
  email text not null check (email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$' and length(email) <= 320),
  phone text check (phone is null or length(phone) <= 40),
  inquiry_type text not null check (length(inquiry_type) between 1 and 100),
  message text not null check (length(message) between 1 and 5000),
  status text not null default 'new' check (status in ('new', 'in_progress', 'completed')),
  created_at timestamptz not null default now()
);

create index if not exists inquiries_created_at_idx on inquiries (created_at desc);

alter table inquiries enable row level security;

-- Public: insert only, and only ever as a fresh 'new' inquiry — a direct
-- REST call can't plant a row that's already 'in_progress'/'completed'.
-- Column defaults (status, created_at, id) are applied before this check
-- runs, so a normal insert that omits `status` still satisfies it.
create policy "inquiries_public_insert" on inquiries
  for insert
  with check (status = 'new');

-- Admin: full read + status/management access. No public select/update/
-- delete policy exists at all, so those actions are unconditionally denied
-- to anyone who isn't in admin_users (RLS with no matching policy = deny).
create policy "inquiries_admin_select" on inquiries
  for select
  using (is_admin());

create policy "inquiries_admin_update" on inquiries
  for update
  using (is_admin())
  with check (is_admin());

create policy "inquiries_admin_delete" on inquiries
  for delete
  using (is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0006_content_revisions.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-G — Content revision history (minimal, not Git-like)
--
-- One generic table covers every admin-editable content table at once —
-- Hero, About/Profile, Impact, Case Studies, Advisory, Career, Contact,
-- and (as a side effect of being generic rather than per-table) Education
-- and Footer too. Before every admin save, the CURRENT row is snapshotted
-- here as jsonb; the actual write then proceeds normally. This is a
-- rolling "undo my last edit(s)" safety net, not a version-control
-- system: no branching, no diffing, no commit graph — just "what did this
-- row look like a moment ago, and can I put that back."
--
-- Deliberately excludes gallery_items/media (see 0007_gallery_soft_delete.sql
-- for that table's own, differently-shaped recovery mechanism) and
-- inquiries (visitor-submitted, not admin-authored content — Phase 3-C's
-- RLS already makes those effectively append-only from the public side).
-- ============================================================================

create table if not exists content_revisions (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  row_id text not null, -- text so it fits both singleton tables (id=1) and uuid-keyed list tables
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists content_revisions_lookup_idx
  on content_revisions (table_name, row_id, created_at desc);

alter table content_revisions enable row level security;

-- Same admin-only shape as every content table's write policy — nobody
-- but an admin session can ever read or write a revision. No update
-- policy at all: revisions are write-once from the client (append,
-- never edited). No client-facing delete policy either — pruning old
-- revisions happens only via the SECURITY DEFINER trigger below, which
-- bypasses RLS the same way is_admin() itself does.
create policy "content_revisions_admin_select" on content_revisions
  for select using (is_admin());

create policy "content_revisions_admin_insert" on content_revisions
  for insert with check (is_admin());

-- Retention cap — keeps at most the 10 most recent snapshots per
-- (table_name, row_id), so this table can't grow unbounded from repeated
-- edits over time. This is the one piece of "policy" here, and it's
-- intentionally simple: no configurable retention window, no archival
-- tier, just "keep the last 10, drop the rest."
create or replace function prune_content_revisions()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from content_revisions
  where table_name = new.table_name
    and row_id = new.row_id
    and id not in (
      select id from content_revisions
      where table_name = new.table_name and row_id = new.row_id
      order by created_at desc
      limit 10
    );
  return new;
end;
$$;

drop trigger if exists content_revisions_prune on content_revisions;
create trigger content_revisions_prune
  after insert on content_revisions
  for each row execute function prune_content_revisions();


-- ============================================================================
-- SOURCE: supabase/migrations/0007_gallery_soft_delete.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-G — Gallery soft delete
--
-- Deleting a gallery photo from the admin no longer immediately and
-- permanently removes its row (or the underlying media/storage file) —
-- it's marked `deleted_at`, disappears from both the public site and the
-- admin's main Gallery list, but can be restored from the admin's Trash
-- view. A separate, explicit "영구 삭제" (permanent delete) action is
-- still available in that Trash view for real cleanup — this migration
-- only changes what the everyday "삭제" action does.
--
-- The public read policy is tightened to match: a soft-deleted photo was
-- never meant to be visible again, unlike is_active
-- (0004_gallery_active_flag.sql), which is a temporary show/hide toggle.
-- src/lib/content/gallery.js additionally filters `deleted_at` client-side
-- as a second, independently-testable layer — see docs/PROJECT_STATUS.md's
-- Phase 3-G entry.
-- ============================================================================

alter table gallery_items
  add column if not exists deleted_at timestamptz;

drop policy if exists "gallery_items_public_read" on gallery_items;
create policy "gallery_items_public_read" on gallery_items
  for select using (deleted_at is null);

-- gallery_items_admin_write (`for all using (is_admin())`) already grants
-- the admin full select/insert/update/delete regardless of deleted_at —
-- unaffected by the policy above, which only replaces the *public* read
-- policy. No change needed there.


-- ============================================================================
-- END OF CONSOLIDATED SETUP
--
-- Next step (manual, not SQL — see the header comment at the top of this
-- file): create your admin login in the Supabase Dashboard, then run the
-- admin_users insert with that user's real UUID. Nothing below this line.
-- ============================================================================
