-- ============================================================================
-- LEO BUSINESS ADVISORY — Production Initial Setup
--
-- Generated by concatenating supabase/migrations/0001_init_schema.sql
-- through 0011_muted_text_contrast_fix.sql, in that exact numeric order, with
-- no SQL statement added, removed, or altered — every table, column, RLS
-- policy, function, trigger, and Storage policy below is byte-identical
-- in meaning to its source migration file. Section dividers below name
-- the source file each block came from, purely for traceability back to
-- supabase/migrations/.
--
-- INTENDED USE: apply this ONCE, in full, top to bottom, in the Supabase
-- SQL Editor of a brand-new project that has none of these objects yet.
-- It is NOT safe to run a second time against the same project — most
-- `create policy` statements below have no `if not exists` guard (Postgres
-- doesn't support one for policies), matching the original migration
-- files exactly; a second run will fail the first time it hits an
-- already-existing policy. This mirrors the source migrations' own
-- behavior — no duplicate-execution guard has been added here that
-- wasn't already present in a given file.
--
-- AFTER running this file, one manual step still has to happen outside
-- SQL (see supabase/README.md and 0002's own header comment below): no
-- one has admin access yet. Create your admin login in the Supabase
-- Dashboard (Authentication → Users → Add user), copy that user's UUID,
-- then run this once, by itself, with the real UUID substituted in:
--
--   insert into admin_users (user_id) values ('<uuid from auth.users>');
--
-- Until that insert runs, RLS on every content table denies all writes
-- to everyone (including a logged-in user) — this is expected, not a
-- bug: public read continues to work throughout.
-- ============================================================================


-- ============================================================================
-- SOURCE: supabase/migrations/0001_init_schema.sql
-- ============================================================================

-- ============================================================================
-- LEO Business Advisory — Admin CMS schema (Phase 2-A design)
--
-- Mirrors src/data/profile.js field-for-field, so a future migration can
-- map values across 1:1 with minimal risk of introducing fact drift.
-- Every bilingual field uses the same _ko/_en column-pair convention
-- already used throughout profile.js — see
-- docs/ADMIN_CMS_ARCHITECTURE.md for the full rationale.
--
-- This file is NOT applied to any real Supabase project yet — no project
-- exists. Run it yourself in the Supabase SQL Editor (or `supabase db
-- push`) once you've created one. See supabase/README.md.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Media library — every uploaded image lives here once; content tables
-- reference it by id instead of duplicating storage paths. storage_path
-- is the object path inside the "site-images" bucket (see
-- 0003_storage_setup.sql).
-- ---------------------------------------------------------------------------
create table if not exists media (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  alt_ko text,
  alt_en text,
  width integer,
  height integer,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Singleton content tables — exactly one row each (id fixed to 1 via the
-- check constraint, so there's never an "which row is live?" ambiguity).
-- ---------------------------------------------------------------------------

create table if not exists site_settings (
  id integer primary key default 1 check (id = 1),
  name text not null,
  title_tag text not null,
  description_en text not null,
  updated_at timestamptz not null default now()
);

create table if not exists person (
  id integer primary key default 1 check (id = 1),
  name_ko text not null,
  name_ko_formatted text not null,
  name_en text not null,
  name_en_display text not null,
  title_ko text not null,
  title_en text not null,
  positioning_ko text not null,
  positioning_en text not null,
  portrait_label_ko text not null,
  portrait_label_en text not null,
  updated_at timestamptz not null default now()
);

-- mailto:/tel: hrefs are derived from email/phone_display in application
-- code, not stored here, so they can never drift out of sync with the
-- displayed value.
create table if not exists contact_info (
  id integer primary key default 1 check (id = 1),
  location_ko text not null,
  location_en text not null,
  email text not null,
  phone_display text not null,
  info_label_ko text not null,
  info_label_en text not null,
  updated_at timestamptz not null default now()
);

create table if not exists hero_content (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null,
  eyebrow_en text not null,
  headline_ko jsonb not null, -- array of lines, e.g. ["Building Brands.", "Scaling Businesses.", ...]
  headline_en jsonb not null,
  subhead_ko text not null,
  subhead_en text not null,
  cta_primary_ko text not null,
  cta_primary_en text not null,
  cta_primary_target text not null, -- target section id, e.g. "impact"
  cta_secondary_ko text not null,
  cta_secondary_en text not null,
  cta_secondary_target text not null,
  hero_image_id uuid references media(id),
  updated_at timestamptz not null default now()
);

create table if not exists about_content (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null,
  eyebrow_en text not null,
  headline_ko text not null,
  headline_en text not null,
  bio_ko text not null,
  bio_en text not null,
  portrait_image_id uuid references media(id),
  updated_at timestamptz not null default now()
);

-- Section heading copy (eyebrow + title) for the sections whose body
-- content is a list, rendered from the list tables below. Kept separate
-- from those lists so editing a heading never risks touching list rows.
create table if not exists impact_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists case_studies_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists advisory_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists career_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null
);

create table if not exists gallery_section (
  id integer primary key default 1 check (id = 1),
  eyebrow_ko text not null, eyebrow_en text not null,
  title_ko text not null, title_en text not null,
  empty_ko text not null, empty_en text not null -- shown when gallery_items has 0 rows
);

create table if not exists contact_cta (
  id integer primary key default 1 check (id = 1),
  headline_ko text not null, headline_en text not null,
  button_ko text not null, button_en text not null
);

-- `labels` shape: { "name": {"ko":"이름","en":"Name"}, "company": {...},
-- "email": {...}, "inquiryType": {...}, "message": {...} } — mirrors
-- profile.js contactForm.labels exactly.
create table if not exists contact_form_content (
  id integer primary key default 1 check (id = 1),
  labels jsonb not null,
  inquiry_placeholder_ko text not null,
  inquiry_placeholder_en text not null,
  submit_ko text not null,
  submit_en text not null,
  note_ko text not null,
  note_en text not null
);

create table if not exists footer_content (
  id integer primary key default 1 check (id = 1),
  copyright_ko text not null, copyright_en text not null,
  back_to_top_ko text not null, back_to_top_en text not null
);

-- ---------------------------------------------------------------------------
-- List content — ordered via sort_order (lets the admin UI reorder rows
-- without changing any other data).
-- ---------------------------------------------------------------------------

create table if not exists impact_metrics (
  id uuid primary key default gen_random_uuid(),
  value_ko text not null, label_ko text not null,
  value_en text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists case_studies (
  id uuid primary key default gen_random_uuid(),
  case_key text not null unique, -- stable slug, matches profile.js caseStudies[].id (e.g. "samsonite-korea")
  tag text not null, -- e.g. "CASE 01"
  title_ko text not null, title_en text not null,
  summary_ko text not null, summary_en text not null,
  image_id uuid references media(id),
  sort_order integer not null default 0
);

create table if not exists case_study_metrics (
  id uuid primary key default gen_random_uuid(),
  case_study_id uuid not null references case_studies(id) on delete cascade,
  value_ko text not null, label_ko text not null,
  value_en text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists case_study_highlights (
  id uuid primary key default gen_random_uuid(),
  case_study_id uuid not null references case_studies(id) on delete cascade,
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists advisory_items (
  id uuid primary key default gen_random_uuid(),
  item_key text not null unique, -- matches profile.js advisory.items[].id
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists career_entries (
  id uuid primary key default gen_random_uuid(),
  period text not null, -- e.g. "2013–2015"
  role_ko text not null, role_en text not null,
  company_ko text not null, company_en text not null,
  sort_order integer not null default 0
);

create table if not exists education_entries (
  id uuid primary key default gen_random_uuid(),
  text_ko text not null, text_en text not null,
  sort_order integer not null default 0
);

create table if not exists inquiry_types (
  id uuid primary key default gen_random_uuid(),
  label_ko text not null, label_en text not null,
  sort_order integer not null default 0
);

create table if not exists gallery_items (
  id uuid primary key default gen_random_uuid(),
  item_key text not null unique, -- matches profile.js gallery[].id
  caption_ko text not null, caption_en text not null,
  image_id uuid references media(id),
  aspect_ratio text not null default '4 / 3', -- CSS aspect-ratio value
  is_wide boolean not null default false,
  sort_order integer not null default 0
);


-- ============================================================================
-- SOURCE: supabase/migrations/0002_rls_policies.sql
-- ============================================================================

-- ============================================================================
-- Row Level Security — public read, admin-only write.
--
-- Run this AFTER 0001_init_schema.sql. admin_users lists which Supabase
-- Auth users are allowed to write content — nobody can just sign up and
-- get write access. After creating your admin login (Supabase Dashboard
-- → Authentication → Users → Add user, or have them sign up once), find
-- their id in that same screen and run:
--
--   insert into admin_users (user_id) values ('<uuid from auth.users>');
-- ============================================================================

create table if not exists admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table admin_users enable row level security;
-- Deliberately no public policies on admin_users — nobody reads/writes it
-- from the client at all; membership is managed directly in the SQL
-- editor by whoever has Supabase project access.

-- `set search_path` pins this security-definer function to the `public`
-- schema (plus pg_temp, needed for temp objects) so a caller can't shadow
-- `admin_users` by creating a same-named table/function earlier in their
-- own search_path — the standard hardening for SECURITY DEFINER
-- functions (Phase 2-G security pass).
create or replace function is_admin()
returns boolean
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select exists (select 1 from admin_users where user_id = auth.uid());
$$;

-- Every content table: anyone (including a signed-out visitor) can read;
-- only a row in admin_users can write. Run each pair after its table
-- exists (i.e. after 0001_init_schema.sql).

alter table site_settings enable row level security;
create policy "site_settings_public_read" on site_settings for select using (true);
create policy "site_settings_admin_write" on site_settings for all using (is_admin()) with check (is_admin());

alter table person enable row level security;
create policy "person_public_read" on person for select using (true);
create policy "person_admin_write" on person for all using (is_admin()) with check (is_admin());

alter table contact_info enable row level security;
create policy "contact_info_public_read" on contact_info for select using (true);
create policy "contact_info_admin_write" on contact_info for all using (is_admin()) with check (is_admin());

alter table hero_content enable row level security;
create policy "hero_content_public_read" on hero_content for select using (true);
create policy "hero_content_admin_write" on hero_content for all using (is_admin()) with check (is_admin());

alter table about_content enable row level security;
create policy "about_content_public_read" on about_content for select using (true);
create policy "about_content_admin_write" on about_content for all using (is_admin()) with check (is_admin());

alter table impact_section enable row level security;
create policy "impact_section_public_read" on impact_section for select using (true);
create policy "impact_section_admin_write" on impact_section for all using (is_admin()) with check (is_admin());

alter table case_studies_section enable row level security;
create policy "case_studies_section_public_read" on case_studies_section for select using (true);
create policy "case_studies_section_admin_write" on case_studies_section for all using (is_admin()) with check (is_admin());

alter table advisory_section enable row level security;
create policy "advisory_section_public_read" on advisory_section for select using (true);
create policy "advisory_section_admin_write" on advisory_section for all using (is_admin()) with check (is_admin());

alter table career_section enable row level security;
create policy "career_section_public_read" on career_section for select using (true);
create policy "career_section_admin_write" on career_section for all using (is_admin()) with check (is_admin());

alter table gallery_section enable row level security;
create policy "gallery_section_public_read" on gallery_section for select using (true);
create policy "gallery_section_admin_write" on gallery_section for all using (is_admin()) with check (is_admin());

alter table contact_cta enable row level security;
create policy "contact_cta_public_read" on contact_cta for select using (true);
create policy "contact_cta_admin_write" on contact_cta for all using (is_admin()) with check (is_admin());

alter table contact_form_content enable row level security;
create policy "contact_form_content_public_read" on contact_form_content for select using (true);
create policy "contact_form_content_admin_write" on contact_form_content for all using (is_admin()) with check (is_admin());

alter table footer_content enable row level security;
create policy "footer_content_public_read" on footer_content for select using (true);
create policy "footer_content_admin_write" on footer_content for all using (is_admin()) with check (is_admin());

alter table media enable row level security;
create policy "media_public_read" on media for select using (true);
create policy "media_admin_write" on media for all using (is_admin()) with check (is_admin());

alter table impact_metrics enable row level security;
create policy "impact_metrics_public_read" on impact_metrics for select using (true);
create policy "impact_metrics_admin_write" on impact_metrics for all using (is_admin()) with check (is_admin());

alter table case_studies enable row level security;
create policy "case_studies_public_read" on case_studies for select using (true);
create policy "case_studies_admin_write" on case_studies for all using (is_admin()) with check (is_admin());

alter table case_study_metrics enable row level security;
create policy "case_study_metrics_public_read" on case_study_metrics for select using (true);
create policy "case_study_metrics_admin_write" on case_study_metrics for all using (is_admin()) with check (is_admin());

alter table case_study_highlights enable row level security;
create policy "case_study_highlights_public_read" on case_study_highlights for select using (true);
create policy "case_study_highlights_admin_write" on case_study_highlights for all using (is_admin()) with check (is_admin());

alter table advisory_items enable row level security;
create policy "advisory_items_public_read" on advisory_items for select using (true);
create policy "advisory_items_admin_write" on advisory_items for all using (is_admin()) with check (is_admin());

alter table career_entries enable row level security;
create policy "career_entries_public_read" on career_entries for select using (true);
create policy "career_entries_admin_write" on career_entries for all using (is_admin()) with check (is_admin());

alter table education_entries enable row level security;
create policy "education_entries_public_read" on education_entries for select using (true);
create policy "education_entries_admin_write" on education_entries for all using (is_admin()) with check (is_admin());

alter table inquiry_types enable row level security;
create policy "inquiry_types_public_read" on inquiry_types for select using (true);
create policy "inquiry_types_admin_write" on inquiry_types for all using (is_admin()) with check (is_admin());

alter table gallery_items enable row level security;
create policy "gallery_items_public_read" on gallery_items for select using (true);
create policy "gallery_items_admin_write" on gallery_items for all using (is_admin()) with check (is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0003_storage_setup.sql
-- ============================================================================

-- ============================================================================
-- Storage bucket for site images.
--
-- Run this AFTER 0002_rls_policies.sql (it depends on admin_users/is_admin()).
--
-- Bucket "site-images" is public-read (this is a public marketing site —
-- there's no reason to gate image loads behind signed URLs) and
-- admin-write only. Suggested folder layout inside the bucket, purely for
-- your own organization (Storage doesn't enforce folder structure) —
-- mirrors profile.js's existing image slots:
--   site-images/hero/
--   site-images/about/
--   site-images/case-studies/
--   site-images/gallery/
-- ============================================================================

-- file_size_limit / allowed_mime_types enforce the same limits as the
-- admin's client-side check (src/admin/content/supabaseStorage.js)
-- server-side too — the client check alone only stops an honest mistake,
-- not a direct API call with a valid admin session, so both layers exist
-- (Phase 2-G security pass).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-images',
  'site-images',
  true,
  5242880, -- 5 MB, matches MAX_IMAGE_BYTES
  array['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'] -- matches ALLOWED_IMAGE_TYPES
)
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "site_images_public_read"
  on storage.objects for select
  using (bucket_id = 'site-images');

create policy "site_images_admin_insert"
  on storage.objects for insert
  with check (bucket_id = 'site-images' and is_admin());

create policy "site_images_admin_update"
  on storage.objects for update
  using (bucket_id = 'site-images' and is_admin());

create policy "site_images_admin_delete"
  on storage.objects for delete
  using (bucket_id = 'site-images' and is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0004_gallery_active_flag.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-B — Gallery active/inactive flag
--
-- Lets an admin temporarily hide a gallery photo (e.g. a photo pending
-- replacement, or one that no longer fits) without deleting its row —
-- deleting also permanently removes the underlying Storage file and media
-- row, which isn't reversible. Adding a boolean flag instead makes hiding
-- a photo a safe, undoable action.
--
-- `default true` so every existing gallery_items row (and any inserted by
-- older client code that doesn't know about this column yet) stays visible
-- with no migration-time data change needed.
--
-- Admin-side only in this phase: src/admin/pages/images/GalleryImages.jsx
-- reads and writes this column, but the public site's gallery query
-- (src/lib/content/gallery.js) is intentionally left untouched — see
-- docs/PROJECT_STATUS.md's Phase 3-B entry for why, and Phase 3-C for the
-- planned follow-up.
-- ============================================================================

alter table gallery_items
  add column if not exists is_active boolean not null default true;


-- ============================================================================
-- SOURCE: supabase/migrations/0005_inquiries.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-C — Business inquiries (Contact Form submissions)
--
-- A visitor-submitted table, unlike every other table in this schema
-- (which are all admin-authored site content). RLS here is the opposite
-- shape from 0002_rls_policies.sql's public-read/admin-write pattern:
-- anyone can INSERT (that's the whole point of a public contact form),
-- nobody but an admin can ever read, update, or delete a row.
--
-- `phone` is nullable and not currently collected by the public form
-- (src/components/ContactForm.jsx keeps only Name/Company/Email/Type of
-- Inquiry/Message, per this phase's explicit "don't add fields that
-- increase visitor input burden" instruction) — the column exists so a
-- future optional Phone field needs only a form change, not a migration.
-- ============================================================================

create table if not exists inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(name) between 1 and 200),
  company text check (company is null or length(company) <= 200),
  email text not null check (email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$' and length(email) <= 320),
  phone text check (phone is null or length(phone) <= 40),
  inquiry_type text not null check (length(inquiry_type) between 1 and 100),
  message text not null check (length(message) between 1 and 5000),
  status text not null default 'new' check (status in ('new', 'in_progress', 'completed')),
  created_at timestamptz not null default now()
);

create index if not exists inquiries_created_at_idx on inquiries (created_at desc);

alter table inquiries enable row level security;

-- Public: insert only, and only ever as a fresh 'new' inquiry — a direct
-- REST call can't plant a row that's already 'in_progress'/'completed'.
-- Column defaults (status, created_at, id) are applied before this check
-- runs, so a normal insert that omits `status` still satisfies it.
create policy "inquiries_public_insert" on inquiries
  for insert
  with check (status = 'new');

-- Admin: full read + status/management access. No public select/update/
-- delete policy exists at all, so those actions are unconditionally denied
-- to anyone who isn't in admin_users (RLS with no matching policy = deny).
create policy "inquiries_admin_select" on inquiries
  for select
  using (is_admin());

create policy "inquiries_admin_update" on inquiries
  for update
  using (is_admin())
  with check (is_admin());

create policy "inquiries_admin_delete" on inquiries
  for delete
  using (is_admin());


-- ============================================================================
-- SOURCE: supabase/migrations/0006_content_revisions.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-G — Content revision history (minimal, not Git-like)
--
-- One generic table covers every admin-editable content table at once —
-- Hero, About/Profile, Impact, Case Studies, Advisory, Career, Contact,
-- and (as a side effect of being generic rather than per-table) Education
-- and Footer too. Before every admin save, the CURRENT row is snapshotted
-- here as jsonb; the actual write then proceeds normally. This is a
-- rolling "undo my last edit(s)" safety net, not a version-control
-- system: no branching, no diffing, no commit graph — just "what did this
-- row look like a moment ago, and can I put that back."
--
-- Deliberately excludes gallery_items/media (see 0007_gallery_soft_delete.sql
-- for that table's own, differently-shaped recovery mechanism) and
-- inquiries (visitor-submitted, not admin-authored content — Phase 3-C's
-- RLS already makes those effectively append-only from the public side).
-- ============================================================================

create table if not exists content_revisions (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  row_id text not null, -- text so it fits both singleton tables (id=1) and uuid-keyed list tables
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists content_revisions_lookup_idx
  on content_revisions (table_name, row_id, created_at desc);

alter table content_revisions enable row level security;

-- Same admin-only shape as every content table's write policy — nobody
-- but an admin session can ever read or write a revision. No update
-- policy at all: revisions are write-once from the client (append,
-- never edited). No client-facing delete policy either — pruning old
-- revisions happens only via the SECURITY DEFINER trigger below, which
-- bypasses RLS the same way is_admin() itself does.
create policy "content_revisions_admin_select" on content_revisions
  for select using (is_admin());

create policy "content_revisions_admin_insert" on content_revisions
  for insert with check (is_admin());

-- Retention cap — keeps at most the 10 most recent snapshots per
-- (table_name, row_id), so this table can't grow unbounded from repeated
-- edits over time. This is the one piece of "policy" here, and it's
-- intentionally simple: no configurable retention window, no archival
-- tier, just "keep the last 10, drop the rest."
create or replace function prune_content_revisions()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from content_revisions
  where table_name = new.table_name
    and row_id = new.row_id
    and id not in (
      select id from content_revisions
      where table_name = new.table_name and row_id = new.row_id
      order by created_at desc
      limit 10
    );
  return new;
end;
$$;

drop trigger if exists content_revisions_prune on content_revisions;
create trigger content_revisions_prune
  after insert on content_revisions
  for each row execute function prune_content_revisions();


-- ============================================================================
-- SOURCE: supabase/migrations/0007_gallery_soft_delete.sql
-- ============================================================================

-- ============================================================================
-- Phase 3-G — Gallery soft delete
--
-- Deleting a gallery photo from the admin no longer immediately and
-- permanently removes its row (or the underlying media/storage file) —
-- it's marked `deleted_at`, disappears from both the public site and the
-- admin's main Gallery list, but can be restored from the admin's Trash
-- view. A separate, explicit "영구 삭제" (permanent delete) action is
-- still available in that Trash view for real cleanup — this migration
-- only changes what the everyday "삭제" action does.
--
-- The public read policy is tightened to match: a soft-deleted photo was
-- never meant to be visible again, unlike is_active
-- (0004_gallery_active_flag.sql), which is a temporary show/hide toggle.
-- src/lib/content/gallery.js additionally filters `deleted_at` client-side
-- as a second, independently-testable layer — see docs/PROJECT_STATUS.md's
-- Phase 3-G entry.
-- ============================================================================

alter table gallery_items
  add column if not exists deleted_at timestamptz;

drop policy if exists "gallery_items_public_read" on gallery_items;
create policy "gallery_items_public_read" on gallery_items
  for select using (deleted_at is null);

-- gallery_items_admin_write (`for all using (is_admin())`) already grants
-- the admin full select/insert/update/delete regardless of deleted_at —
-- unaffected by the policy above, which only replaces the *public* read
-- policy. No change needed there.


-- ============================================================================
-- SOURCE: supabase/migrations/0008_table_grants.sql
-- ============================================================================

-- ============================================================================
-- Production fix — missing PostgreSQL table GRANTs for anon/authenticated
--
-- 0002_rls_policies.sql enables RLS and defines correct policies on every
-- content table, but never grants the underlying SQL table privileges
-- themselves. RLS only *further restricts* rows on an operation a role
-- already has base privilege for — it never grants that base privilege.
-- Supabase normally auto-provisions this via a platform-level default
-- privilege bootstrap, but on this project's real Production database that
-- bootstrap did not cover these tables, so every read (even against a
-- `for select using (true)` public-read policy) failed with a literal
-- PostgreSQL ACL error: "permission denied for table hero_content" (and
-- identically for every other CMS table) — a privilege-layer rejection,
-- distinct from and prior to any RLS policy evaluation.
--
-- This migration records the exact fix already applied and verified
-- directly against the real Production project's SQL Editor, so a future
-- fresh project (via PRODUCTION_INITIAL_SETUP.sql or `supabase db push`)
-- doesn't hit the same gap. RLS policies remain the actual per-row access
-- control layer, unchanged — this only opens the base privilege RLS needs
-- to be evaluated at all.
-- ============================================================================

grant usage on schema public to anon, authenticated;

grant select on all tables in schema public to anon, authenticated;
grant insert, update, delete on all tables in schema public to authenticated;

alter default privileges in schema public
  grant select on tables to anon, authenticated;

alter default privileges in schema public
  grant insert, update, delete on tables to authenticated;


-- ============================================================================
-- SOURCE: supabase/migrations/0009_site_design_settings.sql
-- ============================================================================

-- ============================================================================
-- Phase 4-B — Site design settings (foundation for an admin-editable
-- Design System, built on top of Phase 4-A's CSS token layer)
--
-- Run this AFTER 0002_rls_policies.sql (is_admin()) and 0008_table_grants.sql.
--
-- Single-row "active design configuration" table, same id=1 singleton
-- shape as hero_content/about_content/etc. in 0001_init_schema.sql — one
-- config for the whole site, not per-section. Every column stores a
-- ready-to-use CSS value (a hex color, an rgba() string, a length like
-- "1280px", a plain unitless number) so a future runtime layer can apply
-- a row directly via `document.documentElement.style.setProperty('--x', v)`
-- with no per-field translation logic.
--
-- Defaults below are the exact literal values Phase 4-A's
-- src/styles/variables.css already resolves to today — connecting this
-- table to the site must not change how it looks. See
-- src/lib/content/designSettings.js for the read-side fallback that
-- guarantees the same thing if this table is ever missing/unreachable.
--
-- No admin UI reads or writes this table yet (Phase 4-B is data-layer
-- only) — src/lib/content/designSettings.js's fetch path is the only
-- consumer, and it isn't wired into page rendering yet either.
-- ============================================================================

create table if not exists site_design_settings (
  id integer primary key default 1 check (id = 1),

  -- Typography
  font_ko text not null,
  font_en text not null,
  body_font_size text not null,
  heading_scale numeric not null check (heading_scale > 0),
  line_height numeric not null check (line_height > 0),
  letter_spacing text not null,

  -- Colors
  color_primary text not null,
  color_secondary text not null,
  color_accent text not null,
  color_background text not null,
  color_surface text not null,
  color_text text not null,
  color_text_muted text not null,
  color_border text not null,

  -- Layout
  content_max_width text not null,
  section_spacing text not null,
  card_radius text not null,
  image_radius text not null,

  -- Motion
  motion_level text not null default 'standard'
    check (motion_level in ('minimal', 'standard', 'expressive')),
  image_motion_style text not null default 'none'
    check (image_motion_style in ('none', 'fade', 'zoom', 'parallax')),

  -- Metadata
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table site_design_settings enable row level security;

-- Same public-read/admin-write shape as every other content table
-- (0002_rls_policies.sql): anyone — signed out, signed in, or an admin —
-- can read the active design config (the public site needs it); only a
-- row in admin_users can insert/update it. No delete policy at all —
-- this singleton is never deleted, only ever updated in place.
create policy "site_design_settings_public_read" on site_design_settings
  for select using (true);
create policy "site_design_settings_admin_write" on site_design_settings
  for all using (is_admin()) with check (is_admin());

-- Explicit table GRANTs, not just the RLS policies above — 0008 already
-- grants these broadly across the whole public schema (including via
-- `alter default privileges` for tables created after it), but this
-- table is granted again here explicitly and unconditionally, so its
-- access never depends on exactly which role/session created it. This
-- is the same class of bug 0008 fixed ("permission denied for table X"
-- from a missing GRANT, independent of correct RLS policies) — belt and
-- suspenders, not a reaction to an observed failure this time.
grant select on site_design_settings to anon, authenticated;
grant insert, update, delete on site_design_settings to authenticated;

-- Seed the single active row with Phase 4-A's current literal values.
-- `on conflict do nothing` — if this ever re-runs after a real admin has
-- already customized the row, their values are never clobbered.
insert into site_design_settings (
  id,
  font_ko, font_en, body_font_size, heading_scale, line_height, letter_spacing,
  color_primary, color_secondary, color_accent, color_background, color_surface,
  color_text, color_text_muted, color_border,
  content_max_width, section_spacing, card_radius, image_radius,
  motion_level, image_motion_style
) values (
  1,
  '''Pretendard'', ''Noto Sans KR'', -apple-system, BlinkMacSystemFont, sans-serif',
  '''Inter'', ''Pretendard'', ''Noto Sans KR'', -apple-system, BlinkMacSystemFont, sans-serif',
  '1rem', 1.333, 1.75, 'normal',
  '#0b1625', '#f4f1ea', '#a4865c', '#f4f1ea', '#ffffff',
  '#222222', '#8b8984', 'rgba(34, 34, 34, 0.12)',
  '1280px', '6rem', '2px', '2px',
  'standard', 'none'
)
on conflict (id) do nothing;


-- ============================================================================
-- SOURCE: supabase/migrations/0010_storage_size_limit.sql
-- ============================================================================

-- ============================================================================
-- Phase 4-H — lower the site-images Storage bucket's file_size_limit to
-- match the tightened client-side MAX_IMAGE_BYTES
-- (src/admin/content/supabaseStorage.js).
--
-- Run this AFTER 0003_storage_setup.sql (which created the bucket).
--
-- 0003 already made this exact insert idempotent via `on conflict (id) do
-- update` — this migration doesn't edit that file (existing migrations
-- are never modified, only added to), it just re-runs the same upsert
-- with the new value, same as how 0008 added GRANTs and 0009 added a new
-- table rather than rewriting an earlier file.
--
-- 2 MB is still generous for a correctly-sized web photo (see
-- src/admin/content/imageGuidelines.js's recommended pixel dimensions —
-- the largest recommended slot is 1600x1200) — this only stops a
-- dramatically oversized/unoptimized upload, most importantly onto the
-- LCP-critical Hero slot. This is a validation-ceiling change only: it
-- does NOT touch, recompress, or delete any file already sitting in the
-- bucket — an existing upload larger than 2MB stays exactly as it is and
-- keeps being served normally; only a NEW upload is now checked against
-- the lower limit (both client-side and here, server-side).
-- ============================================================================

update storage.buckets
set file_size_limit = 2097152 -- 2 MB, matches MAX_IMAGE_BYTES
where id = 'site-images';


-- ============================================================================
-- END OF CONSOLIDATED SETUP
--
-- Next step (manual, not SQL — see the header comment at the top of this
-- file): create your admin login in the Supabase Dashboard, then run the
-- admin_users insert with that user's real UUID. Nothing below this line.
-- ============================================================================


-- ============================================================================
-- SOURCE: supabase/migrations/0011_muted_text_contrast_fix.sql
-- ============================================================================

-- ============================================================================
-- Phase 5-A — fix the site_design_settings default row's muted-text color
-- so it meets WCAG AA (4.5:1) for normal body text against the ivory
-- background, per Phase 4-I's known limitation (~3.10:1 with #8b8984).
--
-- Run this AFTER 0009_site_design_settings.sql (which created the table
-- and seeded row id=1). This migration doesn't edit that file (existing
-- migrations are never modified, only added to) — it just updates the
-- one column that changed, same pattern 0008/0009/0010 already used.
--
-- New value #696764 is the same warm neutral hue family as the original
-- #8b8984 (just darkened), not a different color direction — contrast is
-- 4.98:1 against #f4f1ea (background) and 5.64:1 against #ffffff
-- (surface), both comfortably above the 4.5:1 AA threshold for normal
-- text. src/styles/variables.css's --color-gray literal default was
-- updated to the same value in the same Phase 5-A change, so a fresh
-- checkout with no Supabase configured (or Supabase unreachable) already
-- renders this corrected color via the CSS fallback alone; this
-- migration brings an already-provisioned Production row in sync with
-- that same fallback value.
--
-- Guarded by `where color_text_muted = '#8b8984'`: if an admin has
-- already customized this color through Admin > Settings, their choice
-- is never overwritten — this only touches a row still holding the
-- original Phase 4-A seed value.
-- ============================================================================

update site_design_settings
set color_text_muted = '#696764'
where id = 1
  and color_text_muted = '#8b8984';


-- ============================================================================
-- SOURCE: supabase/migrations/0012_noto_sans_unification.sql
-- ============================================================================

-- ============================================================================
-- Typography unification — the whole site now renders a single font
-- family: Noto Sans, with Noto Sans KR as its Korean-glyph companion
-- (loaded via Google Fonts — see index.html). This replaces the previous
-- Pretendard-led Korean stack and Inter-led English stack in the
-- site_design_settings default row's font_ko/font_en columns.
--
-- Run this AFTER 0009_site_design_settings.sql (which created the table
-- and seeded row id=1). This migration doesn't edit that file (existing
-- migrations are never modified, only added to) — it just updates the two
-- columns that changed, same pattern 0008/0009/0010/0011 already used.
--
-- src/styles/variables.css's --font-kr/--font-heading/--font-body literal
-- defaults, and src/lib/content/designSettings.js's designSettingsFallback()
-- / FONT_SAFETY_FALLBACK, were updated to the same new stack in the same
-- change, so a fresh checkout with no Supabase configured (or Supabase
-- unreachable) already renders Noto Sans via the CSS fallback alone; this
-- migration brings an already-provisioned Production row in sync with
-- that same fallback value.
--
-- Guarded by `where font_ko = '...' and font_en = '...'` (the exact
-- literals 0009 seeded): if an admin has already customized either font
-- through Admin > Settings, their choice is never overwritten — this only
-- touches a row still holding the original Phase 4-A seed values.
-- ============================================================================

update site_design_settings
set font_ko = '''Noto Sans KR'', ''Noto Sans'', sans-serif',
    font_en = '''Noto Sans'', ''Noto Sans KR'', sans-serif'
where id = 1
  and font_ko = '''Pretendard'', ''Noto Sans KR'', -apple-system, BlinkMacSystemFont, sans-serif'
  and font_en = '''Inter'', ''Pretendard'', ''Noto Sans KR'', -apple-system, BlinkMacSystemFont, sans-serif';


-- ============================================================================
-- SOURCE: supabase/migrations/0013_gallery_video_support.sql
-- ============================================================================

-- ============================================================================
-- Gallery ("비주얼 스토리") video support — allow MP4 uploads into the
-- existing `site-images` Storage bucket alongside photos.
--
-- Run this AFTER 0010_storage_size_limit.sql. This migration doesn't edit
-- 0003/0010 (existing migrations are never modified, only added to) — it
-- re-runs the same bucket upsert those did, with the new mime type/limit,
-- same pattern 0008/0009/0010/0011/0012 already used.
--
-- Two things change together, matching the client-side update in the same
-- change (src/admin/content/supabaseStorage.js's new ALLOWED_GALLERY_TYPES/
-- MAX_VIDEO_BYTES, used only by src/admin/content/useGalleryImages.js —
-- every other upload path, Hero/About/Case Studies, still validates
-- against the original ALLOWED_IMAGE_TYPES/MAX_IMAGE_BYTES, completely
-- unaffected by this file):
--
-- 1. `allowed_mime_types` gains 'video/mp4'.
-- 2. `file_size_limit` rises from 2MB to 20MB (MAX_VIDEO_BYTES) — this is
--    a single bucket-wide ceiling (Storage has no per-mime-type limit), so
--    it becomes the outer bound for every upload into this bucket,
--    photos included. The tighter 2MB photo limit is still enforced by
--    the client (validateGalleryFile/validateImageFile) — same "client is
--    the real per-type gate, server is a hard ceiling against a direct API
--    call" layering 0003's own comment already describes; a non-image,
--    non-video-mp4 file is still rejected outright by allowed_mime_types
--    regardless of size.
-- ============================================================================

update storage.buckets
set file_size_limit = 20971520, -- 20 MB, matches MAX_VIDEO_BYTES
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'video/mp4']
where id = 'site-images';


-- ============================================================================
-- SOURCE: supabase/migrations/0014_gallery_more_video_formats.sql
-- ============================================================================

-- ============================================================================
-- Gallery ("비주얼 스토리") — accept more video/animated-image formats
-- beyond the MP4-only support 0013 added: GIF, WebM, QuickTime (.mov), and
-- AVI.
--
-- Run this AFTER 0013_gallery_video_support.sql. This migration doesn't
-- edit that file (existing migrations are never modified, only added to)
-- — it re-runs the same bucket upsert with the expanded mime type list,
-- same pattern 0008/.../0013 already used.
--
-- file_size_limit is unchanged (20MB, still MAX_VIDEO_BYTES) — only the
-- allowed_mime_types list grows. Client-side, src/admin/content/
-- supabaseStorage.js's matching change (VIDEO_MIME_TYPES gains webm/
-- quicktime/x-msvideo, ALLOWED_GALLERY_TYPES gains image/gif) is what
-- validateGalleryFile() actually enforces per-type; every other upload
-- path (Hero/About/Case Studies) is untouched. See that file's own
-- comment on AVI specifically: accepted and stored like any other file,
-- but no major browser ships a native AVI demuxer/codec, so playback
-- through ImagePlaceholder's <video> is not guaranteed the way MP4/WebM/
-- MOV playback is.
-- ============================================================================

update storage.buckets
set allowed_mime_types = array[
  'image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'image/gif',
  'video/mp4', 'video/webm', 'video/quicktime', 'video/x-msvideo'
]
where id = 'site-images';


-- ============================================================================
-- SOURCE: supabase/migrations/0015_gallery_video_size_25mb.sql
-- ============================================================================

-- ============================================================================
-- Gallery ("비주얼 스토리") — raise the video upload ceiling from 20MB to
-- 25MB.
--
-- Run this AFTER 0013_gallery_video_support.sql (which first set
-- file_size_limit to 20MB alongside allowed_mime_types). This migration
-- doesn't edit 0013/0014 (existing migrations are never modified, only
-- added to) — it re-runs the same bucket upsert with the new limit, same
-- pattern 0008/.../0014 already used.
--
-- file_size_limit is a single bucket-wide ceiling (Storage has no
-- per-mime-type limit), so this also nominally raises the outer bound for
-- photo uploads — but the tighter 2MB photo ceiling (MAX_IMAGE_BYTES) is,
-- and always was, enforced client-side only; nothing here changes that.
-- src/admin/content/supabaseStorage.js's MAX_VIDEO_BYTES was updated to
-- the same 25MB in the same change.
-- ============================================================================

update storage.buckets
set file_size_limit = 26214400 -- 25 MB, matches MAX_VIDEO_BYTES
where id = 'site-images';
